In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
##Example sentence
sent =[
    'I am good',
    'I am a good developer',
    'Machine learning and Deep learning',
    'Predictive analytics',
    'classification and regression',
    'Gen AI',
    'Update with latest technology trends',
    'AI is emerging',
]

In [3]:
## Define vocabulary size
voc_size =10000


In [4]:
## One hot Representation
one_hot_rep = [one_hot(words,voc_size) for words in sent]
one_hot_rep

[[3469, 7485, 2253],
 [3469, 7485, 2286, 2253, 8377],
 [3676, 6439, 9409, 5710, 6439],
 [1588, 7584],
 [3752, 9409, 9778],
 [1510, 9040],
 [6544, 9674, 7377, 4940, 1153],
 [9040, 9516, 5532]]

In [5]:
#word embedding representation
from tensorflow.keras.layers import Embedding,Input
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences

In [6]:
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=5

In [9]:
embedded_docs= pad_sequences(one_hot_rep,padding="post",maxlen=sent_length)

In [10]:
print(embedded_docs)

[[3469 7485 2253    0    0]
 [3469 7485 2286 2253 8377]
 [3676 6439 9409 5710 6439]
 [1588 7584    0    0    0]
 [3752 9409 9778    0    0]
 [1510 9040    0    0    0]
 [6544 9674 7377 4940 1153]
 [9040 9516 5532    0    0]]


In [11]:
#feature representation
dim=8

In [12]:
model=Sequential([
    #nput(shape=(5,)),
    Embedding(input_dim=voc_size,output_dim=dim)
])
  
model.compile('adam','mse')

In [13]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step


array([[ 4.2142119e-02,  1.0093521e-02,  8.6225569e-05,  5.4691918e-03,
        -7.9863146e-04,  4.4859480e-02, -1.0423481e-02, -4.7355462e-02],
       [-1.2079965e-02,  2.4370775e-03,  2.2021305e-02,  4.3871436e-02,
         1.3496269e-02, -4.4635892e-02, -2.2418333e-02, -2.4119616e-03],
       [-3.5497595e-02, -3.4543622e-02,  2.3350302e-02, -2.6789917e-02,
        -5.7684667e-03,  8.9240298e-03,  7.0931688e-03,  2.9348258e-02],
       [-1.3045788e-02, -4.5560252e-02, -2.7289167e-03, -4.3274987e-02,
         1.7294120e-02,  2.8015200e-02, -2.3316598e-02,  1.2307536e-02],
       [-1.3045788e-02, -4.5560252e-02, -2.7289167e-03, -4.3274987e-02,
         1.7294120e-02,  2.8015200e-02, -2.3316598e-02,  1.2307536e-02]],
      dtype=float32)

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (5, 8)                 │        80,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 80,000 (312.50 KB)

 Trainable params: 80,000 (312.50 KB)

 Non-trainable params: 0 (0.00 B)